name: "CDK for Terraform Cloudwatch Alarm"
on:
   pull_request:
    branches:
     - main

    types: [opened, synchronize, reopened, closed]
    paths:
      - "*.ts"
      - "cloudwatch_configs.csv"
      - ".github/workflows/cdktf_cloudwatchalarm.yml"
      - ".github/workflows/cdktf_standard_shared.yml"

   workflow_dispatch:

permissions:
  pull-requests: write
  id-token: write
  contents: read

#-------------------------#
jobs:
  deploy-tf:
    uses: ./.github/workflows/cdktf_standard_shared.yml
    with:
      MY_ENV: cloudwatch_alarm
      MY_DIR: cloudwatch_alarm
      MY_STACK: cloudwatch_alarm
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
